<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/1_25_Pandas Cleaning.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [1]:
# !pip install -U datasets
import pandas as pd
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

---

## 🟩 Sort by Salary (1.25.1)

In [2]:
df.sort_values('salary_year_avg', ascending=False,inplace=True)
df.head(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
554784,Data Scientist,Data Scientist,"Madison, SD",via Cooperative Career Center,Full-time,False,"Illinois, United States",2023-05-04 19:06:06,False,True,United States,year,960000.0,NaN,"East River Electric Power Cooperative, Inc.","['java', 'c++', 'python', 'r']","{'programming': ['java', 'c++', 'python', 'r']}"
665811,Senior Data Scientist,Senior Data Scientist,"Pretoria, South Africa",via Adzuna,Full-time,False,South Africa,2023-11-02 10:31:43,False,False,South Africa,year,890000.0,NaN,MSP Staffing LTD,"['python', 'sql', 'java', 'c#', 'databricks', ...","{'cloud': ['databricks', 'azure'], 'libraries'..."
168402,Data Analyst,Data Analyst,Anywhere,via Y Combinator,Full-time,True,India,2023-02-20 15:13:44,True,False,India,year,650000.0,NaN,Mantys,None,None
387378,Data Scientist,Geographic Information Systems Analyst - GIS A...,"New York, NY",via ZipRecruiter,Full-time,False,"New York, United States",2023-12-27 18:00:12,False,False,United States,year,585000.0,NaN,ReServe,['excel'],{'analyst_tools': ['excel']}
160521,Data Scientist,Staff Data Scientist/Quant Researcher,Anywhere,via LinkedIn,Full-time,True,Sudan,2023-08-16 16:11:58,False,False,Sudan,year,550000.0,NaN,Selby Jennings,"['python', 'sql']","{'programming': ['python', 'sql']}"
404932,Data Engineer,Hybrid - Data Engineer - Up to $600k,"New York, NY",via LinkedIn,Full-time,False,"Florida, United States",2023-04-05 16:10:48,False,False,United States,year,525000.0,NaN,Durlston Partners,"['python', 'c++']","{'programming': ['python', 'c++']}"
554140,Data Scientist,Staff Data Scientist - Business Analytics,Anywhere,via LinkedIn,Full-time,True,"Texas, United States",2023-09-01 19:24:02,False,False,United States,year,525000.0,NaN,Selby Jennings,['sql'],{'programming': ['sql']}
417241,Senior Data Scientist,Senior Data Scientist,Anywhere,via LinkedIn,Full-time,True,"Texas, United States",2023-01-31 16:03:46,False,False,United States,year,475000.0,NaN,Glocomms,None,None
618461,Senior Data Scientist,VP Data Science & Research,"Menlo Park, CA",via LinkedIn,Full-time,False,"California, United States",2023-11-08 12:23:39,False,False,United States,year,463500.0,NaN,WhatsApp,['go'],{'programming': ['go']}
124265,Data Scientist,Data Scientist (L5) - Messaging,"Los Gatos, CA",via IT JobServe,Full-time,False,"California, United States",2023-08-17 08:04:09,False,False,United States,year,450000.0,NaN,Netflix,"['python', 'r', 'sql', 'spark', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['sp..."

---

## 🟩 Create Remote Column (1.25.2)

In [3]:
df['is_remote'] = df['job_work_from_home']

---

## 🟩 Extract Year from Date (1.25.3)

In [4]:
df['job_posted_year'] = pd.to_datetime(df['job_posted_date']).dt.year
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,is_remote,job_posted_year
554784,Data Scientist,Data Scientist,"Madison, SD",via Cooperative Career Center,Full-time,False,"Illinois, United States",2023-05-04 19:06:06,False,True,United States,year,960000.0,NaN,"East River Electric Power Cooperative, Inc.","['java', 'c++', 'python', 'r']","{'programming': ['java', 'c++', 'python', 'r']}",False,2023
665811,Senior Data Scientist,Senior Data Scientist,"Pretoria, South Africa",via Adzuna,Full-time,False,South Africa,2023-11-02 10:31:43,False,False,South Africa,year,890000.0,NaN,MSP Staffing LTD,"['python', 'sql', 'java', 'c#', 'databricks', ...","{'cloud': ['databricks', 'azure'], 'libraries'...",False,2023
168402,Data Analyst,Data Analyst,Anywhere,via Y Combinator,Full-time,True,India,2023-02-20 15:13:44,True,False,India,year,650000.0,NaN,Mantys,None,None,True,2023
387378,Data Scientist,Geographic Information Systems Analyst - GIS A...,"New York, NY",via ZipRecruiter,Full-time,False,"New York, United States",2023-12-27 18:00:12,False,False,United States,year,585000.0,NaN,ReServe,['excel'],{'analyst_tools': ['excel']},False,2023
160521,Data Scientist,Staff Data Scientist/Quant Researcher,Anywhere,via LinkedIn,Full-time,True,Sudan,2023-08-16 16:11:58,False,False,Sudan,year,550000.0,NaN,Selby Jennings,"['python', 'sql']","{'programming': ['python', 'sql']}",True,2023

---

## 🟨 Drop Missing Salaries (1.25.4)

In [5]:
df.dropna(subset = ['salary_year_avg'], inplace=True)
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,is_remote,job_posted_year
554784,Data Scientist,Data Scientist,"Madison, SD",via Cooperative Career Center,Full-time,False,"Illinois, United States",2023-05-04 19:06:06,False,True,United States,year,960000.0,NaN,"East River Electric Power Cooperative, Inc.","['java', 'c++', 'python', 'r']","{'programming': ['java', 'c++', 'python', 'r']}",False,2023
665811,Senior Data Scientist,Senior Data Scientist,"Pretoria, South Africa",via Adzuna,Full-time,False,South Africa,2023-11-02 10:31:43,False,False,South Africa,year,890000.0,NaN,MSP Staffing LTD,"['python', 'sql', 'java', 'c#', 'databricks', ...","{'cloud': ['databricks', 'azure'], 'libraries'...",False,2023
168402,Data Analyst,Data Analyst,Anywhere,via Y Combinator,Full-time,True,India,2023-02-20 15:13:44,True,False,India,year,650000.0,NaN,Mantys,None,None,True,2023
387378,Data Scientist,Geographic Information Systems Analyst - GIS A...,"New York, NY",via ZipRecruiter,Full-time,False,"New York, United States",2023-12-27 18:00:12,False,False,United States,year,585000.0,NaN,ReServe,['excel'],{'analyst_tools': ['excel']},False,2023
160521,Data Scientist,Staff Data Scientist/Quant Researcher,Anywhere,via LinkedIn,Full-time,True,Sudan,2023-08-16 16:11:58,False,False,Sudan,year,550000.0,NaN,Selby Jennings,"['python', 'sql']","{'programming': ['python', 'sql']}",True,2023

---