<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/2_10_Pandas Applying Functions.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

## 🟩 Convert Date to String (2.10.1)

In [12]:
df['job_posted_date_str'] = df['job_posted_date'].apply(lambda date: date.strftime('%Y-%m-%d'))
df[['job_posted_date_str', 'job_posted_date']]

       job_posted_date_str     job_posted_date
0               2023-06-16 2023-06-16 13:44:15
1               2023-01-14 2023-01-14 13:18:07
2               2023-10-10 2023-10-10 13:14:55
3               2023-07-04 2023-07-04 13:01:41
4               2023-08-07 2023-08-07 14:29:36
...                    ...                 ...
785736          2023-03-13 2023-03-13 06:16:16
785737          2023-03-12 2023-03-12 06:18:18
785738          2023-03-12 2023-03-12 06:32:36
785739          2023-03-12 2023-03-12 06:32:15
785740          2023-03-13 2023-03-13 06:16:31

[785741 rows x 2 columns]

---

## 🟨 Days Since Posted (2.10.2)

In [13]:
from datetime import datetime

df['days_since_posted'] = df['job_posted_date'].apply(lambda date: (datetime.now() - date).days)
df[['days_since_posted', 'job_posted_date']]

        days_since_posted     job_posted_date
0                    1116 2023-06-16 13:44:15
1                    1269 2023-01-14 13:18:07
2                    1000 2023-10-10 13:14:55
3                    1098 2023-07-04 13:01:41
4                    1064 2023-08-07 14:29:36
...                   ...                 ...
785736               1211 2023-03-13 06:16:16
785737               1212 2023-03-12 06:18:18
785738               1212 2023-03-12 06:32:36
785739               1212 2023-03-12 06:32:15
785740               1211 2023-03-13 06:16:31

[785741 rows x 2 columns]

---

## 🟥 Salary Category (2.10.3)

In [11]:
df_filtered = df.dropna(subset='salary_year_avg').copy()
df_filtered['salary_category'] = df['salary_year_avg'].apply(lambda sal: 'Low' if sal < 60_000 else 'Medium' if sal <= 100_000 else 'High')
df_filtered[['salary_year_avg', 'salary_category']]

        salary_year_avg salary_category
28             109500.0            High
77             140000.0            High
92             120000.0            High
100            228222.0            High
109             89000.0          Medium
...                 ...             ...
785624         139216.0            High
785641         150000.0            High
785648         221875.0            High
785682         157500.0            High
785692         157500.0            High

[22003 rows x 2 columns]

---